# Generated by Django 4.2 on 2024-05-04 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('contact_details', models.TextField()),
                ('address', models.TextField(max_length=225)),
                ('vendor_code', models.CharField(max_length=50, unique=True)),
                ('on_time_delivery_rate', models.FloatField(default=0)),
                ('quality_rating_avg', models.FloatField(default=0)),
                ('average_response_time', models.FloatField(default=0)),
                ('fulfillment_rate', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'vendors',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('po_number', models.CharField(max_length=225, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(null=True)),
                ('items', models.JSONField()),
                ('quantity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=25)),
                ('quality_rating', models.FloatField(default=0)),
                ('issue_date', models.DateTimeField(null=True)),
                ('acknowledgment_date', models.DateTimeField(null=True)),
                ('fk_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_vendor', to='core.vendors', verbose_name='Vendor')),
            ],
            options={
                'db_table': 'purchase_orders',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPerformances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('on_time_delivery_rate', models.FloatField(default=0)),
                ('quality_rating_avg', models.FloatField(default=0)),
                ('average_response_time', models.FloatField(default=0)),
                ('fulfillment_rate', models.FloatField(default=0)),
                ('fk_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_vendor', to='core.vendors', verbose_name='Vendor')),
            ],
            options={
                'db_table': 'historical_performances',
                'ordering': ['-id'],
            },
        ),
    ]
