# Generated by Django 4.2 on 2024-05-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='completed_date',
            field=models.DateTimeField(null=True),
        ),
    ]
